import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Heading, Container, Center } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <Container>
      <Box>
        <Head>
          <title>Web3 Calendar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Center>
          <Heading>Web3 Calendar</Heading>
        </Center>
      </Box>
    </Container>
  )
}

export default Home
